name: hr_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.7+10

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  win32: ^5.6.0
  archive: ^3.6.1
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  cached_network_image: ^3.3.0
  calendar_view: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.1.2
  flutter_image_slideshow: ^0.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.0
  geolocator: ^10.1.0
  get_it: ^7.6.4
  gif: ^2.3.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.7.0
  mockito: ^5.4.4
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  slide_digital_clock: ^1.0.3
  one_clock: ^2.0.1
  permission_handler: ^11.3.1
  dio: ^5.7.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.7

flutter_native_splash:
 color: '#FFFFFF'
 image: 'assets/images/logo.png'
 android_12:
   color: '#FFFFFF'
   image: 'assets/images/logo.png'
 android: true
 ios: true
 fullscreen: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/loader.json
    - assets/lottie/reports.json
    - assets/lottie/employee-intro.json
    - assets/lottie/attendance.json
    - assets/lottie/arrow-up.json
    - assets/lottie/slide-up.json
    - assets/lottie/manager.json
    - assets/lottie/employee.json
    - assets/lottie/eye-loader.json





  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
